### ISSUE TITLE
Can't get coverage data when running from Gitlab

### ISSUE THREAD

**Issue by tflorac** [coveragepy/coveragepy#1285]
**Describe the bug**
I'm using Gitlab to run unit tests.
I have a"test" command which is generated using zc.buildout and zc.recipe.testrunner.
When run locally, everything is OK, the "coverage report" display coverage statistics. But when run from Gitlab, the output is:
```
/usr/local/lib/python3.7/site-packages/coverage/control.py:761: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
```

**To Reproduce**
My Gitlab-CI.yml file using Python 3.7 is like this:
```
test-3.7:
    stage: test
    script:
        - pip install anybadge coverage
        - mkdir ./coverage
        - coverage erase
        - coverage run ./bin/test | tee ./coverage/coverage.log
        - coverage xml
        - GLOBAL_COVER=$(coverage report | grep TOTAL | awk '{print $4}' | cut -d '%' -f 1)
        - anybadge --label=Coverage --file=./coverage/coverage.svg --value=$GLOBAL_COVER coverage
        - echo "Global tests coverage is $GLOBAL_COVER %"
    artifacts:
        paths:
            - ./coverage/
            - coverage.xml
```

Job output is like this:
```
$ coverage erase
$ coverage run ./bin/test | tee ./coverage/coverage.log
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Ran 66 tests with 0 failures, 0 errors and 0 skipped in 2.960 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
Coverage.py warning: No data was collected. (no-data-collected)
```

The default version of Coverage is now 6.1.2; I have tried to force installation of release 5.5 which was used until now but the behaviour is still the same.
Versions of zc.buildout and zc.recipe.testrunner are pinned, and so didn't changed.

**Expected behavior**
Coverage data should be reported when using Gitlab.
