### ISSUE TITLE
"source" config combined with pytest-xdist leads to incorrect coverage

### ISSUE THREAD

**Issue by DanCardin** [coveragepy/coveragepy#1341]
**Describe the bug**
Either source behaves weirdly in combination with xdist, or the documentation around
how source/include work could be improved.

When supplying certain source/include values in particular ways with xdist, you can
either get 0% or 100%.

In my real-life usecase, I actually see 16% coverage reported,
where the *last* xdist process reports some amount of coverage while everything
else reports 0. But perhaps due to the simpler test-setup i lay out below, it only
seems to result in 0s.

It seems, by description, similar to https://github.com/nedbat/coveragepy/issues/389

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using? 3.9.6
1. What version of coverage.py shows the problem? 6.3.2
1. What versions of what packages do you have installed? pytest-xdist==2.5.0

```
❯ tree
.
├── poetry.lock
├── pyproject.toml
├── src
│  └── foo
│     ├── __init__.py
│     └── meow.py
└── test.py
```

```toml
# pyproject.toml
[tool.poetry]
name = "foo"
version = "0.0.0"
description = ""
authors = []
packages = [
    { include = "foo", from = "src" },
]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.coverage.run]
source = ["src"]
parallel = true
branch = true
```

```python
# meow.py
def meow():
    print("meow")


def meow2():
    print("meow")


def meow3():
    print("meow")


meow()
```

```
# test.py
from foo.meow import meow, meow2, meow3


def test_meow():
    meow()


def test_meow2():
    meow2()


def test_meow3():
    meow3
```

If you run the following, you get the correct result (86% in this case)
```bash
coverage run -m py.test test.py && coverage combine && coverage report
```

If you run the following, you get 0%
```
coverage run -m py.test -n 3 test.py && coverage combine && coverage report
```

Perhaps notable other options I tried:
```toml
source = ["src/"]  # 0%
source = ["foo"]  # 0%
source = ["src/foo"]  # 0%
source = ["src/foo"]  # 0%
include = ["src"]  # 0%
include = ["src/*"]  # 86% hurray!
```

So tl;dr the behavior of source seems to be different with/without xdist, perhaps
in combination given the fact that the package is nested within a src/ directory
instead of `foo/` being implicitly on the path.

**Expected behavior*
I expect the behavior of the `source` option to react the same regardless of
use of the `-n` flag from pytest-xdist.

Alternatively, if this is difficult to work around, just that perhaps the docs
be made more clear that one needs to use `include` with a pattern.

**Comment by ssbarnea** [comment]
I can confirm that there is a clear bug in this area and when I commented `source` and used `include` the reported coverage went from 12% to 23%, even if xdist run on 10 cores (m1).

This is still far from the real coverage on the project, which is around 84% as measured with pytest-cov.

I should mention that I reached that place while trying to avoid using pytest-cov because it was reporting some warnings about modules being imported too soon. Funny bit is that even with these warnings, the pytest-cov reported far more than coverage.

```toml
# pyproject.toml
[tool.coverage.run]
parallel = true
concurrency = ["multiprocessing", "thread"]
```

I am really curious to find a project using just coverage.py + pytest + xdist, what does properly record the coverage, maybe I could stop what is causing the incomplete coverage.

Another thing that I found quite weird was that I seen the coverage files being exact `102400` in file size.
