### ISSUE TITLE
Configurable tabsize in HTML reports

### ISSUE THREAD

**Issue by Paebbels** [coveragepy/coveragepy#1342]
**Is your feature request related to a problem? Please describe.**
In #6, it was reported that `\t` get handled in HTML reports.  
When checking `html.py` this mentioned code seams to be gone.

When using tab characters for indentation in Python files, coverage.py converts all tabs to 8 spaces (checked in Chrome browser).  
When checking the HTML source code, then 8 spaces can be found:

| HTML Code | HTML View |
| --------- | --------- |
| ![image](https://user-images.githubusercontent.com/956109/157745586-2fe36a9f-bccf-4841-9c6c-8c58efdb9347.png) | ![image](https://user-images.githubusercontent.com/956109/157746096-c2b3649b-19c2-427a-af1e-c0578ebb6a9f.png) |

**Describe the solution you'd like**
Offer an option in the configuration file, so the conversion of tab characters to spaces can be specified.

```
[html]
tabstyle = spaces
tabsize = 2
```

Or this

```
[html]
tabstyle = tabs
tabsize = 2
```

This would allow CSS to specify the representation with a default of `2`.

**Describe alternatives you've considered**
1. The documentation contains no options to configure the tab to space translation process.
2. I think modifying CSS is not possible, because the HTML code contains already 8 spaces.  
   So the representation of tab characters can't be modified.

   ```css
   #source { padding: 1em 0 1em 3.5rem; font-family: SFMono-Regular, Menlo, Monaco, Consolas, monospace; }
   #source p { position: relative; white-space: pre; }
   #source p * { box-sizing: border-box; }
   #source p .t { display: inline-block; width: 100%; box-sizing: border-box; margin-left: -.5em; padding-left: 0.3em; border-left: 0.2em solid #fff; }
   ```

**Additional context**
* CSS settings for tab sizes: https://developer.mozilla.org/de/docs/Web/CSS/tab-size  
  `tab-size: 2;`

----------
/cc @umarcor

**Comment by Paebbels** [comment]
Added research about CSS for tabs.

**Comment by nedbat** [comment]
I'd like to handle this by reading .editorconfig files, but that will require some refactoring, and using an optional third-party library.

**Comment by Paebbels** [comment]
The `.editorconfig` sounds also good.

But shouldn't there be a fallback to the `pyproject.toml` or similar?

**Comment by nedbat** [comment]
I would rather not invent a coverage.py-only setting for this.  editorconfig files are good, and more people should use them.

**Comment by Paebbels** [comment]
I also would prefer the `.editorconfig`.

What do you mean by "coverage.py-only"?  
Coverage.py is already reading from `pyproject.toml`.

```toml
[tool.pytest.ini_options]
# Don't set 'python_classes = *' otherwise, pytest doesn't search for classes
# derived from unittest.Testcase
python_files = "*"
python_functions = "test_*"

[tool.coverage.run]
branch = true
omit = [
	"*site-packages*",
	"setup.py"
]

[tool.coverage.report]
skip_covered = true
skip_empty = true
exclude_lines = [
	"raise NotImplementedError"
]

[tool.coverage.html]
directory = "report/coverage/html"

[tool.coverage.xml]
output = "report/coverage/coverage.xml"
```
