### ISSUE TITLE
Configured data-file is not used by xml report

### ISSUE THREAD

**Issue by ssbarnea** [coveragepy/coveragepy#1536]
To my surprise I discovered that configuring a datafile in pyproject.toml does not have any effect on other commands that need a data file, like `xml` report.

```toml
[tool.coverage.run]
data_file = ".tox/.coverage.coverage"
```

I looked and there is no similar option for xml or report and the only way to have a custom location is to define `COVERAGE_FILE` environment variable.

**Comment by nedbat** [comment]
I can't reproduce this.  My pyproject.toml looks like this:
```toml
[tool.coverage.run]
data_file = "pyp.dat"
```
When I run `coverage run prog.py`, I get a pyp.dat file.  When I then run `coverage xml`, I get a coverage.xml file with the right data.  

Does the .tox directory exist? Is there something else in the way?
