### ISSUE TITLE
A pre-commit hook for coveragepy

### ISSUE THREAD

**Issue by senhalil** [coveragepy/coveragepy#1539]
**Is your feature request related to a problem? Please describe.**
Coverage doesn't supply hooks so the user needs to install the coveragepy and invoke it from the local environment from the [pre-commit](https://github.com/pre-commit/pre-commit) hook as follows:

```
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: coverage run -m pytest
        language: system
        pass_filenames: false
        always_run: true
```

However, due to [this](https://github.com/microsoft/vscode-python/issues/10165) 2 years old VSCode bug, git doesn't invoke the command in the active environment which renders the usage of coverage via pre-commit hooks very complicated (if not impossible) for some VS Code users.

**Describe the solution you'd like**
If coveragepy were to supply pre-commit hook description, then coveragepy would become installable via pre-commit and one can just do the following and avoid the VS Code bug.

```
  - repo: https://github.com/nedbat/coveragepy
    rev: 6.5.0
    hooks:
      - id: pytest
        name: pytest
        entry: coverage run -m pytest
        pass_filenames: false
        always_run: true
```

**Describe alternatives you've considered**
I did try the suggestions from the VS Code bug page with no avail (wrapping the coverage is not possible since we work as a team with different environments, wrapping the local git was the most viable option which didn't work in the end). 

**Additional context**
I have never created a hook description so I am not sure how involved this would be but here is  the [documentation](https://github.com/microsoft/vscode-python/issues/10165).
