### ISSUE TITLE
Code coverage failing in GitHub Actions

### ISSUE THREAD

**Issue by sr-murthy** [coveragepy/coveragepy#1933]
**Describe the bug**
Unable to generate code coverage report in GitHub Actions CI (x86_64 / Ubuntu latest / Python 3.10-3.13 runners), while being able to to so locally. The error message is:
```bash
/home/runner/work/<package>/<package>.venv/lib/python3.11/site-packages/coverage/control.py:892: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
```
I can see that the coverage report in CI looks like this:
```bash
---------- coverage: platform linux, python 3.11.11-final-0 ----------
Name                    Stmts   Miss   Cover   Missing
------------------------------------------------------
src/<package>/<moduleA>.py       160    160  0.000%   1-992
src/<package>/<moduleB>.py       32     32  0.000%   1-124
src/<package>/<moduleC>.py      31     31  0.000%   1-198
------------------------------------------------------
TOTAL                     223    223  0.000%
```
while locally it works fine, and looks like this:
```bash
---------- coverage: platform darwin, python 3.12.8-final-0 ----------
Name                    Stmts   Miss Branch BrPart    Cover   Missing
---------------------------------------------------------------------
src/<package>/<moduleA>.py       160    160      0      0   0.000%   1-992
src/<package>/<moduleB>.py       32     32      2      0   0.000%   1-124
src/<package>/<moduleC>.py      31      5      8      0  82.051%   177-198
---------------------------------------------------------------------
TOTAL                     223    197     10      0  13.734%
```
The CI step to run tests and generate code coverage is:
```bash
pdm run -v pytest -v
```
The `coverage` version is `>=7.6.12` (so, the latest as of today), and `pytest-cov` is used also.
**To Reproduce**

Python versions:- 3.10-3.13, fails on all four versions

Coverage version:- >= 7.6.12.

This is `pip freeze | sort -f`:
```bash
anyio==4.8.0
asttokens==3.0.0
black==25.1.0
blinker==1.9.0
certifi==2025.1.31
click==8.1.8
coverage==7.6.12
decorator==5.2.1
dep-logic==0.4.11
distlib==0.3.9
et_xmlfile==2.0.0
execnet==2.1.1
executing==2.2.0
filelock==3.17.0
findpython==0.6.2
h11==0.14.0
hishel==0.1.1
httpcore==1.0.7
httpx==0.28.1
idna==3.10
iniconfig==2.0.0
installer==0.7.0
ipdb==0.13.13
ipython==8.32.0
jedi==0.19.2
markdown-it-py==3.0.0
matplotlib-inline==0.1.7
mdurl==0.1.2
msgpack==1.1.0
mypy-extensions==1.0.0
numpy==2.2.3
openpyxl==3.1.5
packaging==24.2
pandas==2.2.3
parso==0.8.4
pathspec==0.12.1
pbs-installer==2025.2.12
pdm==2.22.3
pexpect==4.9.0
pillow==11.1.0
platformdirs==4.3.6
pluggy==1.5.0
prompt_toolkit==3.0.50
ptyprocess==0.7.0
pure_eval==0.2.3
Pygments==2.19.1
pyproject_hooks==1.2.0
pytest-cov==6.0.0
pytest-xdist==3.6.1
pytest==8.3.5
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2025.1
resolvelib==1.1.0
rich==13.9.4
ruff==0.9.7
shellingham==1.5.4
six==1.17.0
sniffio==1.3.1
socksio==1.0.0
stack-data==0.6.3
tabulate==0.9.0
tomlkit==0.13.2
traitlets==5.14.3
truststore==0.10.1
typing_extensions==4.12.2
tzdata==2025.1
unearth==0.17.2
virtualenv==20.29.2
wcwidth==0.2.13
```
The command that runs the tests in CI is:
```bash
pdm run -v pytest
```
where the test configuration comes from the project TOML:
```toml
...
[tool.pytest.ini_options]
pythonpath = "src/<package>"
addopts = """\
    --cache-clear 
    --code-highlight=yes \
    --color=yes \
    --cov=src/<package> \
    --cov-config=pyproject.toml \
    --cov-report=term-missing:skip-covered \
    --dist worksteal \
    --numprocesses=auto \
    -ra \
    --tb=native \
    --verbosity=3\
"""
filterwarnings = [
    "ignore::DeprecationWarning"
]
python_files = ["test_*.py",]
python_classes = ["Test", "Acceptance",]
python_functions = ["test"]
testpaths = [
    "tests/units",
]
markers = [
    # Test tags/labels/markers - not using any currently
]

# For ``coverage`` configuration see the reference from version ``7.4.1``:
#
#     https://coverage.readthedocs.io/en/7.4.1/config.html
#
[tool.coverage.run]
branch = true
omit = [
    "./build",
    "./dist",
    "./docs",
    "*/tests*",
    ".pytest_cache",
    "*.pyc",
    "*.env",
    "*__pycache__*",
    "version.py"
]
source = ["src/<package>"]

[tool.coverage.report]
precision = 3
show_missing = true
skip_covered = true
skip_empty = true
sort = "Name"
...
```
**Expected behavior**
A code coverage step that works and looks the same as what I'm seeing locally when I run `pdm run -v pytest -v`.

**Additional context**
