### ISSUE TITLE
7.7.* degraded performance

### ISSUE THREAD

**Issue by alexei** [coveragepy/coveragepy#1959]
I noticed our CI workflows have gotten slower lately. I did some investigations and found it happened on Apr 1st and so far I was able to isolate it to when we upgraded coverage from 7.6.12 to 7.8.0

In short, previously our tests took 10-15 min. now they take ~15-20 min:

<img width="1167" alt="Image" src="https://github.com/user-attachments/assets/d8944028-d236-4d94-89ce-5a446932e23f" />

<img width="1170" alt="Image" src="https://github.com/user-attachments/assets/0b354afc-d36d-4738-9102-f91c80a44c8b" />

I think we have added 1.5% more tests in the past month, so I ran all the tests we have today in main under multiple versions of the coverage library:

<img width="913" alt="Image" src="https://github.com/user-attachments/assets/296f6c38-5e07-468b-a76b-568444a9c959" />

We use Python 3.12.7 and fwiw we run tests with `COVERAGE_CORE=sysmon` since Mar 2024.

I'd appreciate any suggestions in helping either me or you figure this out.

**Comment by nedbat** [comment]
The other factors are the same? Same version of Python?  What are your coverage settings?

**Comment by alexei** [comment]
Thanks for the response!

The workflows in the screenshot differ in the coveragepy version only.

Config is:

```toml
[tool.coverage.run]
branch = true
source = ["."]

[tool.coverage.report]
omit = [
    "*/migrations/*",
]
skip_empty = true
fail_under=79
precision=2
```
