### ISSUE TITLE
Encoding issues with .so files produced by Cython

### ISSUE THREAD

**Issue by MaxHalford** [coveragepy/coveragepy#934]
**Describe the bug**
I have `.pyx` source files which contain some doctests. When I cythonize them, I obtain some `.so` files. These `.so` files are picked up by `pytest` because they contain some doctests. When I run `coverage run -m pytest` I get the following error: `SyntaxError: invalid or missing encoding declaration`.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*.
1. What version of Python are you using? I'm using Python 3.7.6.
2. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.

```
version: 4.5.4
             coverage: /Users/mhalford/opt/anaconda3/envs/creme/lib/python3.7/site-packages/coverage/__init__.py
          cover_paths: /Users/mhalford/opt/anaconda3/envs/creme/lib/python3.7/site-packages/coverage
          pylib_paths: /Users/mhalford/opt/anaconda3/envs/creme/lib/python3.7
               tracer: CTracer
 plugins.file_tracers: Cython.Coverage.Plugin
  plugins.configurers: -none-
         config_files: .coveragerc
         configs_read: .coveragerc
            data_path: /Users/mhalford/projects/creme-ml/creme/.coverage
               python: 3.7.6 (default, Jan  8 2020, 13:42:34) [Clang 4.0.1 (tags/RELEASE_401/final)]
             platform: Darwin-19.2.0-x86_64-i386-64bit
       implementation: CPython
           executable: /Users/mhalford/opt/anaconda3/envs/creme/bin/python
                  cwd: /Users/mhalford/projects/creme-ml/creme
                 path:
                       /Users/mhalford/opt/anaconda3/envs/creme/lib/python37.zip
                       /Users/mhalford/opt/anaconda3/envs/creme/lib/python3.7
                       /Users/mhalford/opt/anaconda3/envs/creme/lib/python3.7/lib-dynload
                       /Users/mhalford/opt/anaconda3/envs/creme/lib/python3.7/site-packages
                       /Users/mhalford/projects/creme-ml/creme
          environment: -none-
         command_line: /Users/mhalford/opt/anaconda3/envs/creme/bin/coverage debug sys
         source_match: -none-
    source_pkgs_match: -none-
        include_match: -none-
           omit_match: *__init__.py
                       *.so
          cover_match: /Users/mhalford/opt/anaconda3/envs/creme/lib/python3.7/site-packages/coverage
          pylib_match: /Users/mhalford/opt/anaconda3/envs/creme/lib/python3.7
```

3. What versions of what packages do you have installed? The output of `pip freeze` is helpful.

```
alabaster==0.7.12
appnope==0.1.0
argh==0.26.2
astroid==2.3.3
attrs==19.3.0
Babel==2.8.0
backcall==0.1.0
beautifulsoup4==4.8.2
bleach==3.1.0
certifi==2019.11.28
chardet==3.0.4
coverage==4.5.4
-e git+https://github.com/creme-ml/creme.git@15f211de5f9bd8b47258832f65e3e84a93daba58#egg=creme
css-html-js-minify==2.5.5
cycler==0.10.0
Cython==0.29.14
decorator==4.4.1
defusedxml==0.6.0
doc8==0.8.0
docutils==0.16
entrypoints==0.3
flit==2.2.0
flit-core==2.2.0
graphviz==0.13.2
idna==2.8
imagesize==1.2.0
importlib-metadata==1.5.0
ipykernel==5.1.4
ipython==7.12.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jedi==0.16.0
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
jupyterlab==1.2.6
jupyterlab-server==1.0.6
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
livereload==2.6.1
lxml==4.5.0
m2r==0.2.1
MarkupSafe==1.1.1
matplotlib==3.1.3
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.2.0
nbconvert==5.6.1
nbformat==5.0.4
nbsphinx==0.5.1
nbval==0.9.4
notebook==6.0.3
numpy==1.18.1
packaging==20.1
pandocfilters==1.4.2
parso==0.6.1
pathtools==0.1.2
pbr==5.4.4
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
port-for==0.3.1
prometheus-client==0.7.1
prompt-toolkit==3.0.3
ptyprocess==0.6.0
py==1.8.1
Pygments==2.5.2
pylint==2.4.4
pyobjc-core==6.1
pyobjc-framework-Cocoa==6.1
pyobjc-framework-FSEvents==6.1
pyparsing==2.4.6
pyrsistent==0.15.7
pytest==5.3.5
pytest-cov==2.8.1
pytest-cython==0.1.0
python-dateutil==2.8.1
python-slugify==4.0.0
pytoml==0.1.21
pytz==2019.3
PyYAML==5.3
pyzmq==18.1.1
qtconsole==4.6.0
requests==2.22.0
restructuredtext-lint==1.3.0
scikit-learn==0.22.1
scipy==1.4.1
Send2Trash==1.5.0
six==1.14.0
snowballstemmer==2.0.0
soupsieve==1.9.5
Sphinx==2.3.1
sphinx-autobuild==0.7.1
sphinx-copybutton==0.2.8
sphinx-material==0.0.23
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
stevedore==1.31.0
terminado==0.8.3
testpath==0.4.4
text-unidecode==1.3
torch==1.4.0
tornado==6.0.3
traitlets==4.3.3
Unidecode==1.1.1
urllib3==1.25.8
watchdog==0.10.1
wcwidth==0.1.8
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.11.2
zipp==2.1.0
```

4. What code are you running?  Give us a specific commit of a specific repo that we can check out.

You can download the `master` branch of [creme](https://github.com/creme-ml/creme) to check out the error for yourself. The `make cython` command builds the Cython code.

```sh
>>> git clone https://creme-ml.github.io/
>>> cd creme
>>> make cython
```

5. What commands did you run?

```sh
>>> coverage run -m pytest creme/optim
>>> coverage report
```

**Expected behavior**

I'd expect no encoding issue to arise.

**Additional context**

I've tried setting the language-level of Cython to 3 instead of 2 (the default) to no avail.

PS: by the way, great work on this library, I love it.
